[tool.poetry]
name = "quadratic2"
version = "0.1.0"
description = ""
authors = ["Yves Chevallier <yves.chevallier@heig-vd.ch>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
